Models/Details/DetailsDashboardViewModel.cs
using Observe.EntityExplorer.DataObjects;

namespace Observe.EntityExplorer.Models
{
    public class DetailsDashboardViewModel : BaseViewModel
    {
        public ObsDashboard CurrentDashboard { get; set; }

        public DetailsDashboardViewModel(AuthenticatedUser currentUser, ObserveEnvironment observeEnvironment) : base(currentUser, observeEnvironment)
        {
            
        }
    }
}

Models/Details/DetailsDatasetViewModel.cs
using Observe.EntityExplorer.DataObjects;

namespace Observe.EntityExplorer.Models
{
    public class DetailsDatasetViewModel : BaseViewModel
    {
        public ObsDataset CurrentDataset { get; set; }

        public DetailsDatasetViewModel(AuthenticatedUser currentUser, ObserveEnvironment observeEnvironment) : base(currentUser, observeEnvironment)
        {
            
        }
    }
}

Models/Details/DetailsMetricViewModel.cs
using Observe.EntityExplorer.DataObjects;

namespace Observe.EntityExplorer.Models
{
    public class DetailsMetricViewModel : BaseViewModel
    {
        public ObsMetric CurrentMetric { get; set; }
        public List<ObsStage> SearchResults { get; set; }

        public DetailsMetricViewModel(AuthenticatedUser currentUser, ObserveEnvironment observeEnvironment) : base(currentUser, observeEnvironment)
        {
            
        }
    }
}

Models/Details/DetailsMonitor2ViewModel.cs
using Observe.EntityExplorer.DataObjects;

namespace Observe.EntityExplorer.Models
{
    public class DetailsMonitor2ViewModel : BaseViewModel
    {
        public ObsMonitor2 CurrentMonitor { get; set; }

        public DetailsMonitor2ViewModel(AuthenticatedUser currentUser, ObserveEnvironment observeEnvironment) : base(currentUser, observeEnvironment)
        {
            
        }
    }
}

Models/Details/DetailsMonitorViewModel.cs
using Observe.EntityExplorer.DataObjects;

namespace Observe.EntityExplorer.Models
{
    public class DetailsMonitorViewModel : BaseViewModel
    {
        public ObsMonitor CurrentMonitor { get; set; }

        public DetailsMonitorViewModel(AuthenticatedUser currentUser, ObserveEnvironment observeEnvironment) : base(currentUser, observeEnvironment)
        {
            
        }
    }
}

Models/Details/DetailsWorksheetViewModel.cs
using Observe.EntityExplorer.DataObjects;

namespace Observe.EntityExplorer.Models
{
    public class DetailsWorksheetViewModel : BaseViewModel
    {
        public ObsWorksheet CurrentWorksheet { get; set; }

        public DetailsWorksheetViewModel(AuthenticatedUser currentUser, ObserveEnvironment observeEnvironment) : base(currentUser, observeEnvironment)
        {
            
        }
    }
}

Controllers/DetailsController.cs
using System;
using System.Diagnostics;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using NLog;
using Observe.EntityExplorer.DataObjects;
using Observe.EntityExplorer.Models;

namespace Observe.EntityExplorer.Controllers;

public class DetailsController : Controller
{
    public IConfiguration Configuration { get; }
    public IMemoryCache MemoryCache { get; }
    public IWebHostEnvironment HostingEnvironment { get; }
    private readonly ILogger<HomeController> _logger;

    private static Logger logger = LogManager.GetCurrentClassLogger();
    private static Logger loggerConsole = LogManager.GetLogger("Observe.EntityExplorer.Console");
    
    private CommonControllerMethods CommonControllerMethods { get; }

    public DetailsController(ILogger<HomeController> logger, IConfiguration configuration, IWebHostEnvironment hostingEnvironment, IMemoryCache memoryCache)
    {
        this._logger = logger;
        this.Configuration = configuration;
        this.HostingEnvironment = hostingEnvironment; 
        this.MemoryCache = memoryCache;

        this.CommonControllerMethods = new CommonControllerMethods(DetailsController.logger, this.Configuration, this, this.MemoryCache);
    }

    public IActionResult Dataset(
        string userid,
        string id)
    {
        Stopwatch stopWatch = new Stopwatch();
        stopWatch.Start();

        try
        {
            AuthenticatedUser currentUser = this.CommonControllerMethods.GetUser(userid);
            if (currentUser == null)
            {
                return RedirectToAction("Connect", "Connection");
            }
            ObserveEnvironment observeEnvironment = this.CommonControllerMethods.GetObserveEnvironment(currentUser);
            if (observeEnvironment == null)
            {
                throw new Exception("Unable to retrieve the Observe Environment from cache or server");
            }
            DetailsDatasetViewModel viewModel = new DetailsDatasetViewModel(currentUser, observeEnvironment);

            CommonControllerMethods.enrichTrace(currentUser);
            CommonControllerMethods.enrichTrace(observeEnvironment);

            switch (HttpContext.Request.Method)
            {
                case "GET":
                    ObsDataset thisDataset = null;
                    if (observeEnvironment.AllDatasetsDict.TryGetValue(id, out thisDataset) == false)
                    {
                        throw new KeyNotFoundException(String.Format("Unable to retrieve the Observe Dataset {0} from Observe Environment", id));
                    }
                    observeEnvironment.PopulateDatasetStages(currentUser, thisDataset);
                    viewModel.CurrentDataset = thisDataset;
                     
                    break;

                case "POST":
                    break;
            }

            CommonControllerMethods.enrichTrace(viewModel.CurrentDataset);

            return View(viewModel);
        }
        catch (Exception ex)
        {
            logger.Error(ex, ex.Message);
            loggerConsole.Error(ex, ex.Message);

            ViewData["ErrorMessage"] = ex.Message;

            return View(new DetailsDatasetViewModel(null, null));
        }
        finally
        {
            stopWatch.Stop();

            logger.Trace("{0}:{1}/{2}: total duration {3:c} ({4} ms)", HttpContext.Request.Method, this.ControllerContext.RouteData.Values["controller"], this.ControllerContext.RouteData.Values["action"], stopWatch.Elapsed, stopWatch.ElapsedMilliseconds);
            loggerConsole.Trace("{0}:{1}/{2}: total duration {3:c} ({4} ms)", HttpContext.Request.Method, this.ControllerContext.RouteData.Values["controller"], this.ControllerContext.RouteData.Values["action"], stopWatch.Elapsed, stopWatch.ElapsedMilliseconds);
        }
    }

    public IActionResult DatasetOpalExplorer(
        string userid,
        string id)
    {
        Stopwatch stopWatch = new Stopwatch();
        stopWatch.Start();

        try
        {
            AuthenticatedUser currentUser = this.CommonControllerMethods.GetUser(userid);
            if (currentUser == null)
            {
                return RedirectToAction("Connect", "Connection");
            }
            ObserveEnvironment observeEnvironment = this.CommonControllerMethods.GetObserveEnvironment(currentUser);
            if (observeEnvironment == null)
            {
                throw new Exception("Unable to retrieve the Observe Environment from cache or server");
            }
            DetailsDatasetViewModel viewModel = new DetailsDatasetViewModel(currentUser, observeEnvironment);

            CommonControllerMethods.enrichTrace(currentUser);
            CommonControllerMethods.enrichTrace(observeEnvironment);

            switch (HttpContext.Request.Method)
            {
                case "GET":
                    ObsDataset thisDataset = null;
                    if (observeEnvironment.AllDatasetsDict.TryGetValue(id, out thisDataset) == false)
                    {
                        throw new KeyNotFoundException(String.Format("Unable to retrieve the Observe Dataset {0} from Observe Environment", id));
                    }
                    observeEnvironment.PopulateDatasetStages(currentUser, thisDataset);
                    viewModel.CurrentDataset = thisDataset;
                     
                    break;

                case "POST":
                    break;
            }

            CommonControllerMethods.enrichTrace(viewModel.CurrentDataset);

            return View(viewModel);
        }
        catch (Exception ex)
        {
            logger.Error(ex, ex.Message);
            loggerConsole.Error(ex, ex.Message);

            ViewData["ErrorMessage"] = ex.Message;

            return View(new DetailsDatasetViewModel(null, null));
        }
        finally
        {
            stopWatch.Stop();

            logger.Trace("{0}:{1}/{2}: total duration {3:c} ({4} ms)", HttpContext.Request.Method, this.ControllerContext.RouteData.Values["controller"], this.ControllerContext.RouteData.Values["action"], stopWatch.Elapsed, stopWatch.ElapsedMilliseconds);
            loggerConsole.Trace("{0}:{1}/{2}: total duration {3:c} ({4} ms)", HttpContext.Request.Method, this.ControllerContext.RouteData.Values["controller"], this.ControllerContext.RouteData.Values["action"], stopWatch.Elapsed, stopWatch.ElapsedMilliseconds);
        }
    }

    public IActionResult Monitor(
        string userid,
        string id)
    {
        Stopwatch stopWatch = new Stopwatch();
        stopWatch.Start();

        try
        {
            AuthenticatedUser currentUser = this.CommonControllerMethods.GetUser(userid);
            if (currentUser == null)
            {
                return RedirectToAction("Connect", "Connection");
            }
            ObserveEnvironment observeEnvironment = this.CommonControllerMethods.GetObserveEnvironment(currentUser);
            if (observeEnvironment == null)
            {
                throw new Exception("Unable to retrieve the Observe Environment from cache or server");
            }
            DetailsMonitorViewModel viewModel = new DetailsMonitorViewModel(currentUser, observeEnvironment);

            CommonControllerMethods.enrichTrace(currentUser);
            CommonControllerMethods.enrichTrace(observeEnvironment);

            switch (HttpContext.Request.Method)
            {
                case "GET":
                    ObsMonitor thisMonitor = null;
                    if (observeEnvironment.AllMonitorsDict.TryGetValue(id, out thisMonitor) == false)
                    {
                        throw new KeyNotFoundException(String.Format("Unable to retrieve the Observe Monitor {0} from Observe Environment", id));
                    }
                    viewModel.CurrentMonitor = thisMonitor;
                     
                    break;

                case "POST":
                    break;
            }

            CommonControllerMethods.enrichTrace(viewModel.CurrentMonitor);

            return View(viewModel);
        }
        catch (Exception ex)
        {
            logger.Error(ex, ex.Message);
            loggerConsole.Error(ex, ex.Message);

            ViewData["ErrorMessage"] = ex.Message;

            return View(new DetailsMonitorViewModel(null, null));
        }
        finally
        {
            stopWatch.Stop();

            logger.Trace("{0}:{1}/{2}: total duration {3:c} ({4} ms)", HttpContext.Request.Method, this.ControllerContext.RouteData.Values["controller"], this.ControllerContext.RouteData.Values["action"], stopWatch.Elapsed, stopWatch.ElapsedMilliseconds);
            loggerConsole.Trace("{0}:{1}/{2}: total duration {3:c} ({4} ms)", HttpContext.Request.Method, this.ControllerContext.RouteData.Values["controller"], this.ControllerContext.RouteData.Values["action"], stopWatch.Elapsed, stopWatch.ElapsedMilliseconds);
        }
    }

    public IActionResult Monitor2(
        string userid,
        string id)
    {
        Stopwatch stopWatch = new Stopwatch();
        stopWatch.Start();

        try
        {
            AuthenticatedUser currentUser = this.CommonControllerMethods.GetUser(userid);
            if (currentUser == null)
            {
                return RedirectToAction("Connect", "Connection");
            }
            ObserveEnvironment observeEnvironment = this.CommonControllerMethods.GetObserveEnvironment(currentUser);
            if (observeEnvironment == null)
            {
                throw new Exception("Unable to retrieve the Observe Environment from cache or server");
            }
            DetailsMonitor2ViewModel viewModel = new DetailsMonitor2ViewModel(currentUser, observeEnvironment);

            CommonControllerMethods.enrichTrace(currentUser);
            CommonControllerMethods.enrichTrace(observeEnvironment);

            switch (HttpContext.Request.Method)

Views/Details/Metric.cshtml
@using Observe.EntityExplorer.DataObjects;
@using System.Text;

@model Observe.EntityExplorer.Models.DetailsMetricViewModel;

@{
    if (@Model.CurrentMetric != null)
    {
        ViewData["Title"] = String.Format("{0} ({1}) Metric Details", @Model.CurrentMetric.name, @Model.CurrentMetric.datasetName);
    }
}

<p>
    <span class="spanError">@ViewData["ErrorMessage"]</span>
</p>
@if (ViewData["ErrorMessage"] != null)
{
    return;
}

<p>@Html.ActionLink("Back to Home", "Index", "Home", new { userid=@Model.CurrentUser.UniqueID }, null)</p>

@{
    List<ObsStage> datasetStages = Model.SearchResults.Where(s => s.Parent is ObsDataset).ToList();

    List<ObsStage> dashboardStages = Model.SearchResults.Where(s => s.Parent is ObsDashboard).ToList();

    List<ObsStage> monitorStages = Model.SearchResults.Where(s => s.Parent is ObsMonitor).ToList();

    List<ObsStage> monitor2Stages = Model.SearchResults.Where(s => s.Parent is ObsMonitor2).ToList();

    List<ObsStage> worksheetStages = Model.SearchResults.Where(s => s.Parent is ObsWorksheet).ToList();
}

<h1>@Model.ObserveEnvironment.getIconType(@Model.CurrentMetric) Metric Details - @Model.CurrentMetric.name (@Model.CurrentMetric.datasetName)</h1>

<p>
    <a href="#Datasets">@Model.ObserveEnvironment.getIconType(((ObsCompositeObject)new ObsDataset())) Datasets (@datasetStages.Count)</a> 
    <a href="#Dashboards">@Model.ObserveEnvironment.getIconType(new ObsDashboard()) Dashboards (@dashboardStages.Count)</a> 
    <a href="#Monitors">@Model.ObserveEnvironment.getIconType(new ObsMonitor()) Monitors (legacy) (@monitorStages.Count)</a> 
    <a href="#Monitors2">@Model.ObserveEnvironment.getIconType(new ObsMonitor2()) Monitors v2 (@monitor2Stages.Count)</a> 
    <a href="#Worksheets">@Model.ObserveEnvironment.getIconType(new ObsWorksheet()) Worksheets (@worksheetStages.Count)</a> 
</p>

<table>
    <tr>
        <td>Observe</td>
        <td>
            <a href="@String.Format("{0}workspace/{1}/metric-explorer?datasetId={2}&metricName={3}", @Model.CurrentUser.CustomerEnvironmentUrl, @Model.CurrentUser.WorkspaceID, @Model.CurrentMetric.datasetId, @Model.CurrentMetric.name)">📄 Data</a></td>            
        </td>
    <tr>
        <td>Name</td>
        <td>
            @Model.CurrentMetric.name in @Model.CurrentMetric.datasetName (@Model.CurrentMetric.datasetId)
            <br/>
            <code id="searchQuery" class="language-json">"@Model.CurrentMetric.name"</code>
        </td>
    </tr>
    <tr>
        <td>Dataset</td>
        <td>
            @Html.ActionLink("🎫 View", "Dataset", "Details", new { id=@Model.CurrentMetric.datasetId, userid=@Model.CurrentUser.UniqueID }, null) @Model.CurrentMetric.datasetName (@Model.CurrentMetric.datasetId)
        </td>
    </tr>
    <tr>
        <td>Description</td>
        <td>@Model.CurrentMetric.description</td>
    </tr>
    <tr>
        <td>Type</td>
        <td>@Model.CurrentMetric.type</td>
    </tr>
    <tr>
        <td>Unit</td>
        <td>@Model.CurrentMetric.unit</td>
    </tr>
    <tr>
        <td>Rollup</td>
        <td>@Model.CurrentMetric.rollup</td>
    </tr>
    <tr>
        <td>Aggregation</td>
        <td>@Model.CurrentMetric.aggregate</td>
    </tr>
    <tr>
        <td>Interval</td>
        <td>@Model.CurrentMetric.interval</td>
    </tr>
    <tr>
        <td>Bucket Size</td>
        <td>@Model.CurrentMetric.suggestedBucketSize</td>
    </tr>
    <tr>
        <td>State</td>
        <td>@Model.CurrentMetric.state</td>
    </tr>
    <tr>
        <td>Had set_options?</td>
        <td>@Model.CurrentMetric.userDefined</td>
    </tr>
    <tr>
        <td>Heuristics: Cardinality</td>
        <td>@Model.CurrentMetric.cardinality</td>
    </tr>
    <tr>
        <td>Heuristics: Number of Points</td>
        <td>@Model.CurrentMetric.numPoints</td>
    </tr>
    <tr>
        <td>Heuristics: Interval</td>
        <td>@Model.CurrentMetric.discoveredInterval</td>
    </tr>
    <tr>
        <td>Heuristics: Interval StdDev</td>
        <td>@Model.CurrentMetric.discoveredIntervalStdDev</td>
    </tr>
    <tr>
        <td>Last Reported</td>
        <td>@Model.CurrentMetric.lastReported.ToString("u")</td>
    </tr>
    <tr>
        <td>Tags</td>
        <td colspan="2"><pre><code class="language-json">@Model.CurrentMetric.Tags</code></pre></td>
    </tr>
    <tr>
        <td>Link Labels</td>
        <td colspan="2"><pre><code class="language-json">@Model.CurrentMetric.LinkLabels</code></pre></td>
    </tr>
</table>

<input id="checkboxOPALPreviews" type="checkbox" checked="true" value="Show/Hide OPAL Blocks" onclick="showOrHideOPALPreviews(this)"/>
<label for="checkboxOPALPreviews">Show/Hide OPAL Stages</label>

<h2 id="Datasets">@Model.ObserveEnvironment.getIconType(((ObsCompositeObject)new ObsDataset())) Datasets</h2>
<a href="#top">Back to Top</a>

@foreach(ObsStage stage in datasetStages)
{
    ObsDataset entity = (ObsDataset)(stage.Parent);
    <table class="AlternatingRowTable">
        <tr>
            <td><input id="checkboxOPALPreview_@entity.id" type="checkbox" checked="true" value="Show/Hide OPAL" onclick="showOrHideOPALPreview(this, 'code_' + @entity.id)"/> <label for="checkboxOPALPreview_@entity.id">Show/Hide OPAL</label></td>
            <td>@Html.ActionLink("🎫 View", "Dataset", "Details", null, null, stage.id, new { id = entity.id, userid=@Model.CurrentUser.UniqueID, keyword = String.Format("\"{0}\"", @Model.CurrentMetric.name)}, null)</td>
            <td><a href="@String.Format("{0}workspace/{1}/dataset/{2}/{3}", @Model.CurrentUser.CustomerEnvironmentUrl, @Model.CurrentUser.WorkspaceID, @Model.ObserveEnvironment.getDatasetURLPartType(entity), entity.id)">📄 Data</a></td>
            <td>@Model.ObserveEnvironment.getIconType(entity) @entity.kind</td>
            <td>@Model.ObserveEnvironment.getIconOriginType(entity) <span title="@entity.source">@entity.OriginType</span></td>
            <td>@entity.id</td>
            <td>@entity.name</td>
            <td>@stage.name (@stage.id)</td>
            <td>@Model.ObserveEnvironment.getIconWidgetType(stage) @stage.type</td>
        </tr>
    </table>
    <pre id="code_@entity.id"><code class="language-javascript">@stage.pipeline</code></pre>
}

<h2 id="Dashboards">@Model.ObserveEnvironment.getIconType(new ObsDashboard()) Dashboard</h2>
<a href="#top">Back to Top</a>

@foreach(ObsStage stage in dashboardStages)
{
    ObsDashboard entity = (ObsDashboard)(stage.Parent);
    <table class="AlternatingRowTable">
        <tr>
            <td><input id="checkboxOPALPreview_@entity.id" type="checkbox" checked="true" value="Show/Hide OPAL" onclick="showOrHideOPALPreview(this, 'code_' + @entity.id)"/> <label for="checkboxOPALPreview_@entity.id">Show/Hide OPAL</label></td>
            <td>@Html.ActionLink("📈 View", "Dashboard", "Details", null, null, stage.id, new { id = entity.id, userid=@Model.CurrentUser.UniqueID, keyword = String.Format("\"{0}\"", @Model.CurrentMetric.name)}, null)</td>
            <td><a href="@String.Format("{0}workspace/{1}/dashboard/{2}", @Model.CurrentUser.CustomerEnvironmentUrl, @Model.CurrentUser.WorkspaceID, entity.id)">📄 Data</a></td>
            <td>@Model.ObserveEnvironment.getIconOriginType(entity) @entity.OriginType</td>
            <td>@entity.id</td>
            <td>@entity.name</td>
            <td>@stage.name (@stage.id)</td>
            <td>@Model.ObserveEnvironment.getIconWidgetType(stage) @stage.type</td>
        </tr>
    </table>
    <pre id="code_@entity.id"><code class="language-javascript">@stage.pipeline</code></pre>
}

<h2 id="Monitors">@Model.ObserveEnvironment.getIconType(new ObsMonitor()) Monitors (legacy)</h2>
<a href="#top">Back to Top</a>

@foreach(ObsStage stage in monitorStages)
{
    ObsMonitor entity = (ObsMonitor)(stage.Parent);
    <table class="AlternatingRowTable">
        <tr>
            <td><input id="checkboxOPALPreview_@entity.id" type="checkbox" checked="true" value="Show/Hide OPAL" onclick="showOrHideOPALPreview(this, 'code_' + @entity.id)"/> <label for="checkboxOPALPreview_@entity.id">Show/Hide OPAL</label></td>
            <td>@Html.ActionLink("📟 View", "Monitor", "Details", null, null, stage.id, new { id = entity.id, userid=@Model.CurrentUser.UniqueID, keyword = String.Format("\"{0}\"", @Model.CurrentMetric.name)}, null)</td>
            <td><a href="@String.Format("{0}workspace/{1}/monitor/{2}", @Model.CurrentUser.CustomerEnvironmentUrl, @Model.CurrentUser.WorkspaceID, entity.id)">🛠️ Edit</a></td>
            <td>@Model.ObserveEnvironment.getIconOriginType(entity) @entity.OriginType</td>
            <td>@entity.id</td>
            <td>@entity.name</td>
            <td>@stage.name (@stage.id)</td>
            <td>@Model.ObserveEnvironment.getIconWidgetType(stage) @stage.type</td>
        </tr>
    </table>
    <pre id="code_@entity.id"><code class="language-javascript">@stage.pipeline</code></pre>
}

<h2 id="Monitors2">@Model.ObserveEnvironment.getIconType(new ObsMonitor2()) Monitors v2</h2>
<a href="#top">Back to Top</a>

@foreach(ObsStage stage in monitor2Stages)
{
    ObsMonitor2 entity = (ObsMonitor2)(stage.Parent);
  
    <table class="AlternatingRowTable">
        <tr>
            <td><input id="checkboxOPALPreview_@entity.id" type="checkbox" checked="true" value="Show/Hide OPAL" onclick="showOrHideOPALPreview(this, 'code_' + @entity.id)"/> <label for="checkboxOPALPreview_@entity.id">Show/Hide OPAL</label></td>
            <td>@Html.ActionLink("📱 View", "Monitor2", "Details", null, null, stage.id, new { id = entity.id, userid=@Model.CurrentUser.UniqueID, keyword = String.Format("\"{0}\"", @Model.CurrentMetric.name)}, null)</td>
            <td><a href="@String.Format("{0}workspace/{1}/{2}-monitor/{3}", @Model.CurrentUser.CustomerEnvironmentUrl, @Model.CurrentUser.WorkspaceID, @Model.ObserveEnvironment.getMonitorv2URLPartType(entity), entity.id)">🛠️ Edit</a></td>
            <td>@Model.ObserveEnvironment.getIconOriginType(entity) @entity.OriginType</td>
            <td>@entity.id</td>
            <td>@entity.name</td>
            <td>@stage.name (@stage.id)</td>
            <td>@Model.ObserveEnvironment.getIconWidgetType(stage) @stage.type</td>
        </tr>
    </table>
    <pre id="code_@entity.id"><code class="language-javascript">@stage.pipeline</code></pre>
}

<h2 id="Worksheets">@Model.ObserveEnvironment.getIconType(new ObsWorksheet()) Worksheets</h2>
<a href="#top">Back to Top</a>

@foreach(ObsStage stage in worksheetStages)
{
    ObsWorksheet entity = (ObsWorksheet)(stage.Parent);
    <table class="AlternatingRowTable">
        <tr>
            <td><input id="checkboxOPALPreview_@entity.id" type="checkbox" checked="true" value="Show/Hide OPAL" onclick="showOrHideOPALPreview(this, 'code_' + @entity.id)"/> <label for="checkboxOPALPreview_@entity.id">Show/Hide OPAL</label></td>
            <td>@Html.ActionLink("📝 View", "Worksheet", "Details", null, null, stage.id, new { id = entity.id, userid=@Model.CurrentUser.UniqueID, keyword = String.Format("\"{0}\"", @Model.CurrentMetric.name)}, null)</td>
            <td><a href="@String.Format("{0}workspace/{1}/worksheet/{2}", @Model.CurrentUser.CustomerEnvironmentUrl, @Model.CurrentUser.WorkspaceID, entity.id)">📄 Data</a></td>
            <td>@Model.ObserveEnvironment.getIconOriginType(entity) @entity.OriginType</td>
            <td>@entity.id</td>
            <td>@entity.name</td>
            <td>@stage.name (@stage.id)</td>
            <td>@Model.ObserveEnvironment.getIconWidgetType(stage) @stage.type</td>
        </tr>
    </table>
    <pre id="code_@entity.id"><code class="language-javascript">@stage.pipeline</code></pre>
}

<script src="~/js/SearchResults.js" asp-append-version="true"></script>